### ISSUE TITLE
Corrupted addon in latest version of thunderbird 

### ISSUE THREAD

**Issue by TechyAditya** [fullmontis/thunderbird-youtube-thumbnails#2]
<img width="308" alt="image" src="https://github.com/fullmontis/thunderbird-youtube-thumbnails/assets/72063181/6d45fc96-59b9-4e81-8aca-163e816883c3">

**Comment by TechyAditya** [comment]
Workaround: Instead of having nested folders in zip (that's what github's "download as zip" does), all 4 files should be contained in the root folder of the zip.

**Comment by fullmontis** [comment]
Thanks for the feedback, added instructions in the Readme in commit d2c9d7a
