### ISSUE TITLE
Doesn't work in Thunderbird v128.0

### ISSUE THREAD

**Issue by iamalexei** [fullmontis/thunderbird-youtube-thumbnails#3]
After upgrading to Thunderbird v128.0 Youtube thumbnails dissapeared

**Comment by fullmontis** [comment]
Where did you get that Thunderbird version? I'm on the latest version (on which the extension works on for me) and it's 115.12.2

**Comment by iamalexei** [comment]
@fullmontis [Release Notes — Thunderbird](https://www.thunderbird.net/en-US/thunderbird/128.0.1esr/releasenotes/) that's the version which is currently available for download on thunderbird.net

**Comment by fullmontis** [comment]
Oh okay, I was trying to update from app and it said that 115.13.0 was the latest, but apparently the 128.0 version can only be downloaded from the website

It seems like 128.0 is a complete overhaul of the software, so it may require a rewrite. I'll give it an eye later today

**Comment by fullmontis** [comment]
Fixed in ba6577e

**Comment by iamalexei** [comment]
@fullmontis It works again. Thank you!
